# Generated by Django 3.1.3 on 2021-02-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210205_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='default title', max_length=300),
        ),
    ]
